module.exports = function () {
  return {
    vehicles: ([] = [
      {
        vehicleNo: 2001,
        status: "Available",
        model: "2022",
        pricePerKm: 12,
        seater: 5,
        category: "petrol",
        driverName: "John Carter",
        driverNumber: 9876543001,
      },
      {
        vehicleNo: 2002,
        status: "Booked",
        model: "2023",
        pricePerKm: 15,
        seater: 7,
        category: "diesel",
        driverName: "Emily Stone",
        driverNumber: 9876543002,
      },
      {
        vehicleNo: 2003,
        status: "Maintenance",
        model: "2021",
        pricePerKm: 10,
        seater: 4,
        category: "cng",
        driverName: "Michael Lee",
        driverNumber: 9876543003,
      },
      {
        vehicleNo: 2004,
        status: "Available",
        model: "2023",
        pricePerKm: 18,
        seater: 5,
        category: "ev",
        driverName: "Sophia Green",
        driverNumber: 9876543004,
      },
      {
        vehicleNo: 2005,
        status: "Booked",
        model: "2022",
        pricePerKm: 14,
        seater: 6,
        category: "diesel",
        driverName: "Liam Brown",
        driverNumber: 9876543005,
      },
      {
        vehicleNo: 2006,
        status: "Available",
        model: "2020",
        pricePerKm: 11,
        seater: 5,
        category: "petrol",
        driverName: "Olivia White",
        driverNumber: 9876543006,
      },
      {
        vehicleNo: 2007,
        status: "Maintenance",
        model: "2021",
        pricePerKm: 9,
        seater: 4,
        category: "cng",
        driverName: "Noah Black",
        driverNumber: 9876543007,
      },
      {
        vehicleNo: 2008,
        status: "Available",
        model: "2023",
        pricePerKm: 20,
        seater: 5,
        category: "ev",
        driverName: "Ava Gray",
        driverNumber: 9876543008,
      },
      {
        vehicleNo: 2009,
        status: "Booked",
        model: "2022",
        pricePerKm: 13,
        seater: 7,
        category: "diesel",
        driverName: "William Scott",
        driverNumber: 9876543009,
      },
      {
        vehicleNo: 2010,
        status: "Available",
        model: "2021",
        pricePerKm: 10,
        seater: 5,
        category: "petrol",
        driverName: "Isabella Adams",
        driverNumber: 9876543010,
      },
      {
        vehicleNo: 2011,
        status: "Maintenance",
        model: "2020",
        pricePerKm: 8,
        seater: 4,
        category: "cng",
      },
    ]),
    orders: [],
    users: [],
  };
};
